services:
  privoxy:
    image: amartinr/privoxy-ssl-adblock
    container_name: privoxy-ssl-adblock
    ports:
      - 8118:8118
    environment:
      - TZ=Europe/Madrid
      - ADBLOCK_URLS=https://easylist.to/easylist/easylist.txt
      - ADBLOCK_FILTERS=
    volumes:
      - privoxy-ca:/usr/local/etc/privoxy/CA
    restart: unless-stopped
    hostname: "privoxy"

volumes:
  privoxy-ca:
